### ISSUE TITLE
seldon-core-analytics chart (Grafana and prometheus) not working with k8s v.1.22+

### ISSUE THREAD

**Issue by spicoflorin** [mlops-for-all/mlops-for-all.github.io#118]
Hello!
According to https://github.com/SeldonIO/seldon-core/issues/4513, seldon-core analytics was deprecated for new versions of kubernetes.

I've tested out your documentation regarding the installation of the two monitoring components 
as described here,

https://mlops-for-all.github.io/en/docs/setup-components/install-components-pg,

on k3s version Server Version: v1.27.5+k3s1, and I got the same errors as described in https://github.com/SeldonIO/seldon-core/issues/4513, meaning
`Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: [resource mapping not found for name: "seldon-core-analytics-grafana" namespace: "seldon-system" from "": no matches for kind "PodSecurityPolicy" in version "policy/v1beta1"
`
I've added also a new issue on the seldon about the Grafana support for new versions of k8s:

https://github.com/SeldonIO/seldon-core/issues/5134

Do you have any updates on the above issues?

Thanks,
 Florin

**Comment by zamonia500** [comment]
I checked the latest seldon-core documentation and issue you attached.
As you pointed, seldon-core analytics was deprecated and their doc is guiding to use [Prometheus Operator](https://github.com/prometheus-operator/prometheus-operator) now.
I can't guarantee when our manual gonna updated because mlops-for-all is not actively maintained these days :(
But i'll keep it mind this issue, thanks for report this!

**Comment by spicoflorin** [comment]
Hi, @zamonia500 !
 Thank you for your answer. In my opinion, it is a pity that seldon team is no longer support Grafana. Prometheus, at the first glance of a beginner, is too complex to be used as it is.
